Subnomo/prettify
osuosl/timesync-frontend-flask pull request #146
Opened 2016-10-24 20:26 UTC by subnomo

Fixes #33 

This PR still needs work to improve usability, but I believe all that's left are "nice-to-haves," basic functionality should be there. If something is actually broken, please let me know.

## Changes in this PR.

- [X] Materialize existing pages

## Testing this PR.

1. Run `docker-compose build`
2. Start the container with `docker-compose up`
3. Visit http://localhost:5000, browse the site

### Expected Output.

You should see the materialized pages. This is an example from the `/times` page:
![times page](https://cloud.githubusercontent.com/assets/1390653/19662613/215f8c2e-99ed-11e6-9440-29b6e7442443.png)

@osuosl/devs

2016-10-24 22:31 UTC, aaroncohen73 requested changes
Overall, the website design looks pretty good. However, there are some things that aren't working. In addition to some of the notes I've left in the code,
- Table sorting doesn't work at all
- Multiselect inputs on forms appear as if an option is selected even if no option has been selected
- Form clearing doesn't work
- The pagination controls have disappeared entirely for some reason (There's an error in the browser console that might be helpful in figuring that one out).

2016-10-24 22:31 UTC, aaroncohen73 commented on app/templates/create_time.html
> +        {% if form.notes %}
This seems like an unnecessary check to make

2016-10-24 22:31 UTC, aaroncohen73 commented on app/templates/layout.html
> +            <ul id="slide-out" class="side-nav fixed">
The sidenav bar is missing links to create/view projects

2016-10-24 22:31 UTC, aaroncohen73 commented on app/__init__.py
> +indexjs = Bundle('../js/index.js', filters='rjsmin', output='js/index.js')
When this is run after a `docker-compose up`, the files are owned by root. It's not like we'll need to edit these files by hand, but they should be renamed to `*.min.js` and/or put into a separate directory.

2016-10-24 22:31 UTC, aaroncohen73 commented on app/templates/view_users.html
> +    var view_user_times_root = "{{ url_for('view_user_times') }}";
`view_user_times` doesn't work

2016-10-31 22:26 UTC, aaroncohen73 approved these changes

2016-10-31 22:37 UTC, aaroncohen73 commented
There seem to be just a few more things that need fixing before this is ready to merge. Fine-tuning the website design can come later.

- On some pages, not all of the sidebar links appear. For example, on the "Edit time" page the sidebar links to creating activities and projects don't appear. On some pages (The create/view projects pages and all of the edit and delete pages), the sidebar just shows the link to the login page.
- The edit project and view_user_times pages are broken.
- The following form inputs appear to be broken: The members/managers/spectators selection boxes on the "Create Project" page, all of the checkbox inputs

2016-12-02 00:23 UTC, subnomo commented
@aaroncohen73 Thanks for the feedback, everything *should* be fixed now. Of course there are some usability tweaks to make, but that comes later.

2016-12-05 21:01 UTC, Kennric commented
This looks pretty good to me - not perfect, but I'd rather get it in in and fix it than sit on it waiting for perfection.

2016-12-05 21:02 UTC, merged